spring:
  application:
    name: banco
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/banco}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
  ssl:
    enabled: false
  error:
    whitelabel:
      enabled: false
